### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by richarddribeiro** [SverrirValgeirsson/Todour#12]
Hi Sverrir.

Currently I am using Todour version 2.161 in Manjaro Linux, but I am trying to upgrade to version 1.71, as the new version is not available in Manjaro or Arch repositories (Manjaro is based upon it). 

So, I've downloaded the source code and compiled it following your guidance from the main page. I received a warning about Qt versions before compiling it:
```
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
```
The new version worked fine, however  when I close Todour I receive a message of `Segmentation fault (core dumped)` at the terminal.

Can you please help me with the problem?

Thanks,
Richard

**Comment by SverrirValgeirsson** [comment]
Hi Richard. 

Of course! We don't want a segfault.. 
Firstly, the warnings you shouldn't have to care about as long as you are using the same Qt for running as for building. It's a side effect of the shurtcut key implementation. 

Are you running in 32 or 64 bit?  (my Linux builds are normally 32. I don't know if it matters for the segfault). 
What happens if you compile in debug mode and run in the debugging mode of Qt Creator? (I would expect it to stop at the segfault when you exit it). 

What Qt version are you using? 
BR
Sverrir

**Comment by SverrirValgeirsson** [comment]
Hi again. Try pulling down the latest one. I think I found the issue (at least I found a segfault that happens when exiting).  (commit edbaa657cf38f2a107d122bbc9a2e4d4d2e10623)

BR
Sverrir

**Comment by richarddribeiro** [comment]
Hi Sverrir,

It worked!!! No more segment fault after closing Todour! I am very glad for your help.

Answering your questions: 
- I am running a 64 bit linux. 
- I didn't need to activate the debug mode in Qt Creator, because you solved the problem.
- My Qt specs are: 
`Qt 5.13.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.1.0) on "xcb"`

Than you again for all your work with Todour. It is a very useful software for me and makes my life easier.

All the best,
Richard

**Comment by SverrirValgeirsson** [comment]
Thanks for pointing out the issue :) 
Best regards
/s
