### ISSUE TITLE
[question] date format 

### ISSUE THREAD

**Issue by Weej1** [SverrirValgeirsson/Todour#14]
Hi! 

New user here and I think this app is great. Just wondering: is it at all possible to have the program show a  different date format (e.g. my local one is 05/02/2020 for 5th Feb 2020) ? I read the todo.txt repo and nothing emphasised that we Can't use another date format so was wondering if  chanding formats could be considered at all ? Thanks!

**Comment by SverrirValgeirsson** [comment]
Hi.
Todo.txt format is clear that it's YYYY-MM-DD that should be used in the
file itself so that is not changeable, but of course the program itself
could show something else. There is a risk that the user interface would be
a bit confusing though (as the dates would be different in the actual file
and on screen).

I haven't had this request before and I don't know how many think this is
needed, so I won't put it high on the prio list for now.





Den ons 5 feb. 2020 19:21Weej1 <notifications@github.com> skrev:

**Comment by Weej1** [comment]
Hi Sverrir,

Thanks for replying! (a rarity on smaller projects). I totally understand
why you wouldn't want to do this. I'm not a programmer but i think this
would be a nice little project for me to make this change myself ( i assume
a years worth of weekends and tutorials are in my future!) Thanks again!

**Comment by SverrirValgeirsson** [comment]
Hi.
You are most welcome to try to do this yourself :) 
Feel free to contact me if you need advice, I will do my best to help in that case.

**Comment by Weej1** [comment]
Will do! Closing this since I got the answer. Thanks!
