### ISSUE TITLE
Problem with creation and completion dates

### ISSUE THREAD

**Issue by tenbob** [SverrirValgeirsson/Todour#4]
Hi. I am getting widespread problems with dates in the todo.txt file.

(1) If a task has a creation date, this date is NOT displayed in the task list. Why? If a task has a creation date I want to see it.

(2) A creation date can be added automatically to each new task. This works, but you can't see it as noted above.

(3) When you edit a task, any existing creation date is deleted without warning. This is serious as important information is lost.

(4) When you mark a task as complete the completion date is added to the line. But the format is wrong according to the [specification](https://github.com/todotxt/todo.txt). It should look like this 
`x (B) 2018-05-17 2018-05-15 Install shelves`. 

Instead I'm getting 
`x 2018-05-17 (B) 2018-05-15 Install shelves` 
with the priority sandwiched between the dates.

Could you please look into this.

**Comment by SverrirValgeirsson** [comment]
Hi.
1) Because I don't use it and I have a minor issue with how to do it (formatting on the line. I want to be able to have the date text in a different style and that requires some qt gymnastics) 
2) Yep. 
3) That was news. Agree it's serious. Will fix ASAP
4) I'll look into that at the same time as 3)

**Comment by tenbob** [comment]
Hi @SverrirValgeirsson. Thanks for your helpful reply. 

(1) Yes. I can see that it would be tricky to display the date in a different font. Instead, is it possible to simply display the date in the same font? For me this would be better than omitting the date.

(4) Sorry. This may not be a bug after all. There is a contradiction in the specification. Another user has raised an issue [here](https://github.com/todotxt/todo.txt/issues/17). I suppose we should look to the command line script for the definitive implementation. This deletes the priority when you mark a task completed. So the order is not relevant. However, some users may like to keep the priority, in order to analyse the results. (eg I completed all my priority (A) tasks within 3 days).

Thanks for your help.  Bob

**Comment by SverrirValgeirsson** [comment]
Hi again. This took longer than I expected to find time to fix. But its up now in commit 533f282a153c204b496f6906094489c35c561ace.

I will also try to add some kind of showing dates option before releasing this version.

**Comment by SverrirValgeirsson** [comment]
Ok. Dates are now possible to show (only source yet, I haven't made a build). I have made it so that the dates can not be changed in todour but rather are always preserved. So editing a line that is "2018-05-30 Hello" -> "New text where the date is removed" will result in "2018-05-30 New text where the date is removed" thus the dates can not be touched from the edit line. Opinion on that? Is there a use-case to change the dates from todour directly you think?

**Comment by SverrirValgeirsson** [comment]
Can you try it out ? https://nerdur.com/Todour-2.12.dmg or https://nerdur.com/Todour-2.12.exe

**Comment by SverrirValgeirsson** [comment]
Found an error in these. Anyway. A 2.12. will be up soon and there this is fixed :)

**Comment by SverrirValgeirsson** [comment]
Hi. Thanks for all comments. 

On the dates: I read the specification as when I add completion dates to a task, it has to also have a creation date, so I just put the same day as completion in that case.  I guess that behaviour is still wanted, but one might for some reason not want to have the completion date and only the creation date and then the split you suggest makes sense. That also how you're thinking? 

On the prio stuff I am thinking to have a triple option:

- Remove prio at completion
- Move to tag (pri:X)
- Leave as is

I have changed the way dates are handled when editing and it will be in 2.13 (program will not control anything at all, just allow any edit)

**Comment by SverrirValgeirsson** [comment]
Hi. 
Now my brain hurts a little ;)
What setting do you have on dates and how/where does a date disappear? 
Can you give me a simple step by step on how to recreate?

**Comment by dajare** [comment]
> Can you give me a simple step by step on how to recreate?

:) I'll try! ....

1. Set up Todour with the option `[✓] Add dates to lines`. (All my options as set can[ be seen here][i].)
1. Tasks added with now have a "creation date" added automatically—if only one date is included, the todotxt spec understands that as a [creation date][t1]. E.g. 

    `2019-10-18 Mark "Lausanne" assignments +ffcm`

    That task was *created* on 18 Oct 2019. Fine.

1. Now I wish to add a *completion* date. According to the [todo.txt format rules][t2], that date _precedes_ the "creation date". I'm not sure how to do this *in* Todour, so I edit the `todo.txt` file directly in a text editor (I use [textadept][ta]). In the editor, the line now looks like this:

    `2019-10-30 2019-10-18 Mark "Lausanne" assignments +ffcm`

    where "30 Oct 2019" is now the completion date for a task I created on 18 October.  
    SAVE the file in the editor, and exit.

1. Open the `todo.txt` file in Todour. It only *displays* the "new" completion date, but both dates (18 Oct and 30 Oct) are preserved in the file on disk.
1. But now I need to tweak that task: it's not the "Lausanne", but the "Geneva" assignment I should have noted. I edit this in Todour, so it now displays:

    `2019-10-30 Mark "Geneva" assignments +ffcm

1. Re-open the `todo.txt` file in the editor: it now has 

    `2019-10-30 Mark "Geneva" assignments +ffcm`

    **but what I expected it to have was**

    `2019-10-30  2019-10-18 Mark "Geneva" assignments +ffcm`

So an **edit** to the task loses the original creation date.

I hope that's a clear explanation! If this is "behaviour by design", I think I can live with it! ;) But it is counter-intuitive to me. Thanks for your patience, and your help.

[i]: https://i.imgur.com/31sw3uU.png
[t1]: https://github.com/todotxt/todo.txt#rule-2-a-tasks-creation-date-may-optionally-appear-directly-after-priority-and-a-space
[t2]: https://github.com/todotxt/todo.txt#todotxt-format-rules
[ta]: https://foicica.com/textadept/

**Comment by SverrirValgeirsson** [comment]
Hi. 
Thanks. Good guide. 
Can there really be a clompletion date without the "x"? 
The line should read (as far as I have understood the spec):

`x 2019-10-30 2019-10-18 Mark "Lausanne" assignments +ffcm`

And then todour will recognize it. But two dates on a line without an "x" will cause the program to ignore one of them simply because it's only looking for zero or one date on the line. 
Do you prefer using it like that? (without using the  "x" to mark complete)?

**Comment by dajare** [comment]
> Can there really be a completion date without the "x"?

Ahhhh.... You are right (I am not surprised!). I *thought* that the "completion date" was a **projected** completion date (i.e., "get this done BY the specified date"). But [it isn't][c] — it is the date **on which the task was completed** and so, as you rightly point out, is always accompanied by the `x`. 

My misunderstanding! So - if I want to note a "projected" completion date, that can appear somewhere later in my task description.

Apologies for the distraction! Thanks for the clarification. 👍 

[c]: https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space

**Comment by SverrirValgeirsson** [comment]
No worries :)

You can use the due: tag for your projected/planned completion date.
Todour supports both adding them like "due:2019-12-24" or "due:+34d" where
it will calculate the correct day 34 days from now (or +2w or +5m or
whatever you like)

I use that heavily together with the t: (threshold) tag that can be used to
hide or grey out tasks until I want to see them



Den fre 1 nov. 2019 kl 09:56 skrev David <notifications@github.com>:

**Comment by dajare** [comment]
Brilliant! Even better than I realized. And thanks for the extra advice (I had even watched your wee video several times, and still missed how "completion date" worked :/). 

I'm still not very clear on how `t:` (threshold) works, especially in connection with projects/contexts. If you had an example with explanation on the Todour web-page, that would be a help, too! In any case, thanks again.
